### PR TITLE
Dev Shutter

### PR DESCRIPTION
**Pull request by twistermcneal**
Start shutter movment with bus event implementing callback_after_update

### CODE REVIEW

**Comment by Julius2342** [comment]
Can you explain what you did? Then I will port your changes in my branch ...

(looks like I dont really understand the report back mechanism)

**Comment by twistermcneal** [comment]
i implementet the callback and used the update funktion to get the bus event with this i trigger the up or down movement... in my case some shutters dont have a position value so i think the time funktion is a way to stop the cover at a position but  in this case we need a config parameter how long the cover runs from open to close

**Comment by Julius2342** [comment]
Ok, i see, so it looks like it gets more complicated ...

(My actuator has an explicit group address for requesting the position)

**Comment by twistermcneal** [comment]
can your actuator also move to a given position?

**Comment by Julius2342** [comment]
Yes, but this is a different group address

**Comment by Julius2342** [comment]
btw, i added you on skype. Dont know if you use this :)

**Comment by twistermcneal** [comment]
havent it installed at the moment but yes sometimes ....

**Comment by twistermcneal** [comment]
I think i go with my own shutter class for the moment, so we can think later about adding both functions !?

**Comment by Julius2342** [comment]
My goal is to write a library which is suitable for all common KNX products.

Which shutter actuator do you have? Doesn't it support an absolute shutter position group address? 

(I run **GIRA KNX/Shutter Binary Actuator 103800**,  in my system the group address is named "Shutter/Awning position")

**Comment by twistermcneal** [comment]
this one is a Busch Jaeger 6196/43-102 4x Shutter Actuator KNX,
no it does not support an absolute shutter position, only Move Up/down and Stop/tilt.

**Comment by Julius2342** [comment]
Hmm, ic ... *think*.

I think we should do somehting like:

````
    class Direction(Enum):
        UP = 1
        DOWN = 2


    def set_position(self, position):
        if self.group_address_position is not None:
            self.send(self.group_address_position, [0x80, position])
        else
            self.set_position_relative(position)

    dev set_position_relative(self, position):
        relative_position = position - self.position
        direction = Direction.UP if relative_position > 0 else Direction.DOWN

        travel_time_full = travel_time_up if direction == Direction.UP else travel_time_up_down # should be taken from configuration ..

        travel_time = travel_time_full * abs(relative_position) / 100

        if direction == Direction.UP:
           self.set_up()
        else
           self.set_down()

       time.sleep(travel_time)

       self.set_short_down()
````

**Pull request closed without merging**
